### ISSUE TITLE
saving stop motion videos

### ISSUE THREAD

**Issue by kelgolden** [szager/stop-motion#7]
Hello - I am an elementary school librarian and have a class who would like to create stop motion animation videos to share during our STEAM Fair. Their teacher has reported that the videos are no longer saving or if they do when a student tries to retrieve it they get a message that the file is corrupted. Here is a link to the app:

https://chrome.google.com/webstore/detail/stop-motion-animator/dhgmfcabdnkbdhelnooodefedbilcpho?hl=en-US

Is there a way to fix this so their work can be saved?

Thank you for any help.

**Comment by szager-chromium** [comment]
Hi -- the version of the app on github contains a fix for the issue you're describing. Unfortunately, the Chrome Web Store version has fallen behind, and I'm not sure when I'll be able to update it, but the most up-to-date version is always available at:

https://szager.github.io/stop-motion/

**Comment by szager** [comment]
Hi -- the version of the app on github contains a fix for the issue you're describing. Unfortunately, the Chrome Web Store version has fallen behind, and I'm not sure when I'll be able to update it, but the most up-to-date version is always available at:

https://szager.github.io/stop-motion/

**Comment by sandeen** [comment]
Hi @szager - my wife is also an elementary school librarian, and has a bunch of sad kids with unplayable videos. Was the fix for this problem commit d5f549f45c92dc7fd708167d35b9a0c6bd7f2bc5 / "Fix for VP8X?"

For files that were saved without this fix, is there any possible way to salvage them? It appears that the .ivf stream contains an appropriate number of frames, but I don't know what format they are. If I could possibly extract them, I could reassemble a movie and save these kids' hard work.

I'm happy to hack around here, but would appreciate any pointers (or a "nope, all the data is lost" answer, too.) Thanks!

**Comment by szager** [comment]
> Hi @szager - my wife is also an elementary school librarian, and has a bunch of sad kids with unplayable videos. Was the fix for this problem commit [d5f549f](https://github.com/szager/stop-motion/commit/d5f549f45c92dc7fd708167d35b9a0c6bd7f2bc5) / "Fix for VP8X?"
> 
> For files that were saved without this fix, is there any possible way to salvage them? It appears that the .ivf stream contains an appropriate number of frames, but I don't know what format they are. If I could possibly extract them, I could reassemble a movie and save these kids' hard work.

Using the live version, you should be able to open any previously-saved animation, from any version of the app. If you turn around and save the animation again, it should be a valid and playable webm file.

Hope that helps, let me know if you're still having trouble.

**Comment by sandeen** [comment]
Hey thanks for the reply.

Unfortunately, the saved file seems corrupt and not loadable.  I guess what happened was it treated the VP8X frames as bare VP8, and so it has part of the ICCP frame, and other junk before the otherwise-valid VP8 chunk.

However, I was able to extract the proper VP8 bitstreams to recreate valid individual webp images, and use them to recreate the video with ffmpeg.  It's not the most user friendly thing right now, but given all the sad kids using the chrome web store version, maybe it'd be worth cleaning up and making available to rescue the mangled files... I'll see what I can do.

**Comment by szager-chromium** [comment]
@sandeen If you can give me a link to an example of a broken video, that would be very helpful.
